apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: 10.5.15
      helm:
        releaseName: grafana
        valueFiles:
          - $yamar-repo/infra/resources/values/grafana-values.yaml

    - repoURL: 'https://github.com/letDouglas/yamar.git'
      targetRevision: feature/lgtm-stack-fix
      ref: yamar-repo

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
