apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: kafka
    targetRevision: 32.4.3
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/letDouglas/yamar/main/infra/k8s/helm/kafka-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true