apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mongodb
    targetRevision: 14.2.3
    helm:
      releaseName: mongodb
      valueFiles:
        - https://raw.githubusercontent.com/letDouglas/yamar/main/infra/k8s/helm/mongo-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true