apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/letDouglas/yamar.git'
    targetRevision: HEAD
    path: infra/k8s/apps/mysql
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
