apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  sources:
    - repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
      chart: opentelemetry-collector
      targetRevision: 0.143.0
      helm:
        releaseName: otel-collector
        valueFiles:
          - $yamar-repo/infra/resources/values/otel-collector-values.yaml

    - repoURL: 'https://github.com/letDouglas/yamar.git'
      targetRevision: main
      ref: yamar-repo

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
