apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-schema-registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: schema-registry
    targetRevision: 26.0.5
    helm:
      releaseName: kafka
      valueFiles:
        - https://raw.githubusercontent.com/letDouglas/yamar/main/infra/k8s/helm/schema-registry-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true