apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default

  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: tempo
      targetRevision: 1.10.3
      helm:
        releaseName: tempo
        valueFiles:
          - $yamar-repo/infra/resources/values/tempo-values.yaml

    - repoURL: 'https://github.com/letDouglas/yamar.git'
      targetRevision: main
      ref: yamar-repo

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
