apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/letDouglas/yamar.git'
    targetRevision: HEAD
    path: infra/charts/yamar-service
    helm:
      valueFiles:
        - ../../values/gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true