nameOverride: "product-service"

image:
  repository: "ghcr.io/letdouglas/yamar-product-service"
  tag: "latest"
  pullPolicy: Always

service:
  port: 8041

contextPath: "/api/v1"

env:
  - name: SPRING_DATA_MONGODB_HOST
    value: "mongodb"
  - name: SPRING_DATA_MONGODB_PORT
    value: "27017"
  - name: SPRING_DATA_MONGODB_DATABASE
    value: "product"
  - name: SPRING_DATA_MONGODB_USERNAME
    value: "derain"
  - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
    value: "product"
  - name: ELASTIC_URL
    value: "http://elasticsearch:9200"

secretEnv:
  - name: SPRING_DATA_MONGODB_PASSWORD
    secretKey: mongodb-passwords
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    secretKey: auth0-issuer-uri

initContainers:
  - name: wait-for-mongodb
    image: busybox:latest
    command:
      - sh
      - -c
      - until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done
  - name: wait-for-elasticsearch
    image: busybox:latest
    command:
      - sh
      - -c
      - until wget -q --spider http://elasticsearch:9200; do echo waiting for elastic; sleep 2; done
